name: lrc_parser
description: An ANTLR4-based library to parse, validate, and edit LRC lyrics file. Supports normal, word and hybrid level of lyrics with time-shifting capabilities.
version: 0.0.1
repository: https://github.com/infinitetmy/lrc-parser-dart
environment:
  sdk: ^3.8.1

dependencies:
  antlr4: 4.13.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.29.0
